version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"