version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
  bot:
    container_name: bot
    image: bot
    volumes:
      - /home/ubuntu/task_teb_team:/bot